# Bibliotecas utilizadas

In [50]:
import pandas as pd
import json
import requests
import numpy as np

# 📌 Extracão

In [72]:
# Extraindo dados da APi

url ='https://raw.githubusercontent.com/ingridcristh/challenge2-data-science/refs/heads/main/TelecomX_Data.json' #Importante usar o link para o raw file

resposta = requests.get(url) 
dados_json = resposta.json()

df = pd.json_normalize(dados_json, sep ='_') # Normalizar dados_json para dados aninhados virarem colunas isoladas. usar seperador para visualizar nomes das colunas com '_' ao invés de '.'

In [47]:
df.head(10)

,customerID,Churn,customer_gender,customer_SeniorCitizen,customer_Partner,customer_Dependents,customer_tenure,phone_PhoneService,phone_MultipleLines,internet_InternetService,...,internet_OnlineBackup,internet_DeviceProtection,internet_TechSupport,internet_StreamingTV,internet_StreamingMovies,account_Contract,account_PaperlessBilling,account_PaymentMethod,account_Charges_Monthly,account_Charges_Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.60,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.90,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.90,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.00,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.90,267.4
5,0013-MHZWF,No,Female,0,No,Yes,9,Yes,No,DSL,...,No,No,Yes,Yes,Yes,Month-to-month,Yes,Credit card (automatic),69.40,571.45
6,0013-SMEOE,No,Female,1,Yes,No,71,Yes,No,Fiber optic,...,Yes,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),109.70,7904.25
7,0014-BMAQU,No,Male,0,Yes,No,63,Yes,Yes,Fiber optic,...,No,No,Yes,No,No,Two year,Yes,Credit card (automatic),84.65,5377.8
8,0015-UOCOJ,No,Female,1,No,No,7,Yes,No,DSL,...,No,No,No,No,No,Month-to-month,Yes,Electronic check,48.20,340.35
9,0016-QLJIS,No,Female,0,Yes,Yes,65,Yes,Yes,DSL,...,Yes,Yes,Yes,Yes,Yes,Two year,Yes,Mailed check,90.45,5957.9

# 🔧 Transformação

## Conhecendo o dataset

In [ ]:
# Verificando os tipos de dados no data frame

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7267 non-null   object
 1   Churn                      7267 non-null   object
 2   customer_gender            7267 non-null   object
 3   customer_SeniorCitizen     7267 non-null   int64
 4   customer_Partner           7267 non-null   object
 5   customer_Dependents        7267 non-null   object
 6   customer_tenure            7267 non-null   int64
 7   phone_PhoneService         7267 non-null   object
 8   phone_MultipleLines        7267 non-null   object
 9   internet_InternetService   7267 non-null   object
 10  internet_OnlineSecurity    7267 non-null   object
 11  internet_OnlineBackup      7267 non-null   object
 12  internet_DeviceProtection  7267 non-null   object
 13  internet_TechSupport       7267 non-null   object
 14  internet_StreamingTV       7267 non-null   object
 15  internet_StreamingMovies   7267 non-null   object
 16  account_Contract           7267 non-null   object
 17  account_PaperlessBilling   7267 non-null   object
 18  account_PaymentMethod      7267 non-null   object
 19  account_Charges_Monthly    7267 non-null   float64
 20  account_Charges_Total      7267 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.2+ MB

In [78]:
# Olhando os tipos de variáveis em cada coluna
# df.dtypes

## Verificando e tratando inconsitências nos dados

### Transformando account_Charges_Total em uma coluna numérica

In [73]:
# Transformando account_Charges_Total em uma coluna numérica
df['account_Charges_Total'] = df['account_Charges_Total'].apply(lambda x: x.replace(' ','0'))



df['account_Charges_Total'] = df['account_Charges_Total'].astype(np.float64)

In [79]:
df['account_Charges_Total'].dtypes

dtype('float64')

### Verificando itens duplicados

In [ ]:
# Verificando duplicados
chaves = df.keys()

for i in range(0,21):
    a = df[chaves[i]].unique()
    print(a)

['0002-ORFBO' '0003-MKNFE' '0004-TLHLJ' ... '9992-UJOEL' '9993-LHIEB'
 '9995-HOTOH']
['No' 'Yes' '']
['Female' 'Male']
[0 1]
['Yes' 'No']
['Yes' 'No']
[ 9  4 13  3 71 63  7 65 54 72  5 56 34  1 45 50 23 55 26 69 11 37 49 66
 67 20 43 59 12 27  2 25 29 14 35 64 39 40  6 30 70 57 58 16 32 33 10 21
 61 15 44 22 24 19 47 62 46 52  8 60 48 28 41 53 68 51 31 36 17 18 38 42
  0]
['Yes' 'No']
['No' 'Yes']
['DSL' 'Fiber optic' 'No']
['No' 'Yes']
['Yes' 'No']
['No' 'Yes']
['Yes' 'No']
['Yes' 'No']
['No' 'Yes']
['One year' 'Month-to-month' 'Two year']
['Yes' 'No']
['Mailed check' 'Electronic check' 'Credit card (automatic)'
 'Bank transfer (automatic)']
[65.6  59.9  73.9  ... 91.75 68.8  67.85]
[ 593.3   542.4   280.85 ...  742.9  4627.65 3707.6 ]
customerID

In [130]:
for i in chaves:
    # print(i)
    # print(len(df[i]))
    duplicados = df[i].unique()
    if len(duplicados) == 7267:
        print(i)

customerID

### verificando valores ausentes

In [85]:
# Verificando valores ausentes NaN

nulos_gerados = df.isna().sum()
nulos_gerados

customerID                   0
Churn                        0
customer_gender              0
customer_SeniorCitizen       0
customer_Partner             0
customer_Dependents          0
customer_tenure              0
phone_PhoneService           0
phone_MultipleLines          0
internet_InternetService     0
internet_OnlineSecurity      0
internet_OnlineBackup        0
internet_DeviceProtection    0
internet_TechSupport         0
internet_StreamingTV         0
internet_StreamingMovies     0
account_Contract             0
account_PaperlessBilling     0
account_PaymentMethod        0
account_Charges_Monthly      0
account_Charges_Total        0
dtype: int64

### Simplificando repostas

In [ ]:
# simplificando respostas para 'no'
df = df.replace(['No internet service', 'No phone service'], 'no')

# print("Valores em phone_MultipleLines:", df['phone_MultipleLines'].unique())
# print("Valores em internet_OnlineSecurity:", df['internet_OnlineSecurity'].unique())

Valores em phone_MultipleLines: ['No' 'Yes']
Valores em internet_OnlineSecurity: ['No' 'Yes']

### Formatação em letras minúsculas

In [136]:
#formatando cabeçalho
df.columns = df.columns.str.lower()
df.columns

Index(['customerid', 'churn', 'customer_gender', 'customer_seniorcitizen',
       'customer_partner', 'customer_dependents', 'customer_tenure',
       'phone_phoneservice', 'phone_multiplelines', 'internet_internetservice',
       'internet_onlinesecurity', 'internet_onlinebackup',
       'internet_deviceprotection', 'internet_techsupport',
       'internet_streamingtv', 'internet_streamingmovies', 'account_contract',
       'account_paperlessbilling', 'account_paymentmethod',
       'account_charges_monthly', 'account_charges_total'],
      dtype='object')

In [143]:
# formatando respostas em minúsculo
colunas_texto = df.select_dtypes(include=['object']).columns

for coluna in colunas_texto:
    df[coluna] = df[coluna].str.lower()

df

,customerid,churn,customer_gender,customer_seniorcitizen,customer_partner,customer_dependents,customer_tenure,phone_phoneservice,phone_multiplelines,internet_internetservice,...,internet_onlinebackup,internet_deviceprotection,internet_techsupport,internet_streamingtv,internet_streamingmovies,account_contract,account_paperlessbilling,account_paymentmethod,account_charges_monthly,account_charges_total
0,0002-orfbo,não,feminino,0,sim,sim,9,sim,não,dsl,...,sim,não,sim,sim,não,anual,sim,cheque por correio,65.60,593.30
1,0003-mknfe,não,masculino,0,não,não,9,sim,sim,dsl,...,não,não,não,não,sim,mensal,não,cheque por correio,59.90,542.40
2,0004-tlhlj,sim,masculino,0,não,não,4,sim,não,fibra ótica,...,não,sim,não,não,não,mensal,sim,cheque eletrônico,73.90,280.85
3,0011-igkff,sim,masculino,1,sim,não,13,sim,não,fibra ótica,...,sim,sim,não,sim,sim,mensal,sim,cheque eletrônico,98.00,1237.85
4,0013-exchz,sim,feminino,1,sim,não,3,sim,não,fibra ótica,...,não,não,sim,sim,não,mensal,sim,cheque por correio,83.90,267.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-lutyd,não,feminino,0,não,não,13,sim,não,dsl,...,não,não,sim,não,não,anual,não,cheque por correio,55.15,742.90
7263,9992-rramn,sim,masculino,0,sim,não,22,sim,sim,fibra ótica,...,não,não,não,não,sim,mensal,sim,cheque eletrônico,85.10,1873.70
7264,9992-ujoel,não,masculino,0,não,não,2,sim,não,dsl,...,sim,não,não,não,não,mensal,sim,cheque por correio,50.30,92.75
7265,9993-lhieb,não,masculino,0,sim,sim,67,sim,não,dsl,...,não,sim,sim,não,sim,dois anos,não,cheque por correio,67.85,4627.65
7266,9995-hotoh,não,masculino,0,sim,sim,63,não,não,dsl,...,sim,sim,não,sim,sim,dois anos,não,cheque eletrônico,59.00,3707.60

### Traduzindo para o portugues

In [142]:
dicionario_traducao = {
    'Yes': 'Sim',
    'No': 'Não',
    'Male': 'Masculino',
    'Female': 'Feminino',
    'Month-to-month': 'Mensal',
    'One year': 'Anual',
    'Two year': 'Dois anos',
    'Electronic check': 'Cheque eletrônico',
    'Mailed check': 'Cheque por correio',
    'Bank transfer (automatic)': 'Transferência bancária (automática)',
    'Credit card (automatic)': 'Cartão de crédito (automático)',
    'Fiber optic': 'Fibra ótica'
}

df = df.replace(dicionario_traducao)

df

,customerid,churn,customer_gender,customer_seniorcitizen,customer_partner,customer_dependents,customer_tenure,phone_phoneservice,phone_multiplelines,internet_internetservice,...,internet_onlinebackup,internet_deviceprotection,internet_techsupport,internet_streamingtv,internet_streamingmovies,account_contract,account_paperlessbilling,account_paymentmethod,account_charges_monthly,account_charges_total
0,0002-ORFBO,Não,Feminino,0,Sim,Sim,9,Sim,Não,DSL,...,Sim,Não,Sim,Sim,Não,Anual,Sim,Cheque por correio,65.60,593.30
1,0003-MKNFE,Não,Masculino,0,Não,Não,9,Sim,Sim,DSL,...,Não,Não,Não,Não,Sim,Mensal,Não,Cheque por correio,59.90,542.40
2,0004-TLHLJ,Sim,Masculino,0,Não,Não,4,Sim,Não,Fibra ótica,...,Não,Sim,Não,Não,Não,Mensal,Sim,Cheque eletrônico,73.90,280.85
3,0011-IGKFF,Sim,Masculino,1,Sim,Não,13,Sim,Não,Fibra ótica,...,Sim,Sim,Não,Sim,Sim,Mensal,Sim,Cheque eletrônico,98.00,1237.85
4,0013-EXCHZ,Sim,Feminino,1,Sim,Não,3,Sim,Não,Fibra ótica,...,Não,Não,Sim,Sim,Não,Mensal,Sim,Cheque por correio,83.90,267.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,Não,Feminino,0,Não,Não,13,Sim,Não,DSL,...,Não,Não,Sim,Não,Não,Anual,Não,Cheque por correio,55.15,742.90
7263,9992-RRAMN,Sim,Masculino,0,Sim,Não,22,Sim,Sim,Fibra ótica,...,Não,Não,Não,Não,Sim,Mensal,Sim,Cheque eletrônico,85.10,1873.70
7264,9992-UJOEL,Não,Masculino,0,Não,Não,2,Sim,Não,DSL,...,Sim,Não,Não,Não,Não,Mensal,Sim,Cheque por correio,50.30,92.75
7265,9993-LHIEB,Não,Masculino,0,Sim,Sim,67,Sim,Não,DSL,...,Não,Sim,Sim,Não,Sim,Dois anos,Não,Cheque por correio,67.85,4627.65
7266,9995-HOTOH,Não,Masculino,0,Sim,Sim,63,Não,Não,DSL,...,Sim,Sim,Não,Sim,Sim,Dois anos,Não,Cheque eletrônico,59.00,3707.60

### Transformando Sim e Não em binários

In [144]:
map_bin = {
    'sim': 1,
    'não': 0
}

df = df.replace(map_bin)

df

C:\Users\Otavio\AppData\Local\Temp\ipykernel_5872\1850693792.py:6: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(map_bin)

,customerid,churn,customer_gender,customer_seniorcitizen,customer_partner,customer_dependents,customer_tenure,phone_phoneservice,phone_multiplelines,internet_internetservice,...,internet_onlinebackup,internet_deviceprotection,internet_techsupport,internet_streamingtv,internet_streamingmovies,account_contract,account_paperlessbilling,account_paymentmethod,account_charges_monthly,account_charges_total
0,0002-orfbo,0,feminino,0,1,1,9,1,0,dsl,...,1,0,1,1,0,anual,1,cheque por correio,65.60,593.30
1,0003-mknfe,0,masculino,0,0,0,9,1,1,dsl,...,0,0,0,0,1,mensal,0,cheque por correio,59.90,542.40
2,0004-tlhlj,1,masculino,0,0,0,4,1,0,fibra ótica,...,0,1,0,0,0,mensal,1,cheque eletrônico,73.90,280.85
3,0011-igkff,1,masculino,1,1,0,13,1,0,fibra ótica,...,1,1,0,1,1,mensal,1,cheque eletrônico,98.00,1237.85
4,0013-exchz,1,feminino,1,1,0,3,1,0,fibra ótica,...,0,0,1,1,0,mensal,1,cheque por correio,83.90,267.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-lutyd,0,feminino,0,0,0,13,1,0,dsl,...,0,0,1,0,0,anual,0,cheque por correio,55.15,742.90
7263,9992-rramn,1,masculino,0,1,0,22,1,1,fibra ótica,...,0,0,0,0,1,mensal,1,cheque eletrônico,85.10,1873.70
7264,9992-ujoel,0,masculino,0,0,0,2,1,0,dsl,...,1,0,0,0,0,mensal,1,cheque por correio,50.30,92.75
7265,9993-lhieb,0,masculino,0,1,1,67,1,0,dsl,...,0,1,1,0,1,dois anos,0,cheque por correio,67.85,4627.65
7266,9995-hotoh,0,masculino,0,1,1,63,0,0,dsl,...,1,1,0,1,1,dois anos,0,cheque eletrônico,59.00,3707.60

# 📊 Carga e análise

In [146]:
df.describe()

,customer_seniorcitizen,customer_partner,customer_dependents,customer_tenure,phone_phoneservice,phone_multiplelines,internet_onlinesecurity,internet_onlinebackup,internet_deviceprotection,internet_techsupport,internet_streamingtv,internet_streamingmovies,account_paperlessbilling,account_charges_monthly,account_charges_total
count,7267.000000,7267.000000,7267.000000,7267.000000,7267.000000,7267.000000,7267.000000,7267.000000,7267.000000,7267.000000,7267.000000,7267.000000,7267.000000,7267.000000,7267.000000
mean,0.162653,0.484106,0.300124,32.346498,0.902711,0.421770,0.285950,0.344571,0.342782,0.289528,0.383927,0.387505,0.593230,64.720098,2277.182035
std,0.369074,0.499782,0.458343,24.571773,0.296371,0.493876,0.451897,0.475261,0.474672,0.453575,0.486374,0.487214,0.491265,30.129572,2268.648587
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,18.250000,0.000000
25%,0.000000,0.000000,0.000000,9.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,35.425000,396.200000
50%,0.000000,0.000000,0.000000,29.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,70.300000,1389.200000
75%,0.000000,1.000000,1.000000,55.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,89.875000,3778.525000
max,1.000000,1.000000,1.000000,72.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,118.750000,8684.800000

# 📄Relatorio Final